/*
 * vnas
 *
 * VPC NAS 관련 API<br/>https://ncloud.beta-apigw.ntruss.com/vnas/v2
 *
 * API version: 2020-08-27T01:44:24Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vnas

type CommonCode struct {

	// 코드
Code *string `json:"code,omitempty"`

	// 코드명
CodeName *string `json:"codeName,omitempty"`
}
