/*
 * vserver
 *
 * VPC Compute 관련 API<br/>https://ncloud.beta-apigw.ntruss.com/vserver/v2
 *
 * API version: 2020-08-27T03:07:34Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type CommonCode struct {

	// 코드
Code *string `json:"code,omitempty"`

	// 코드명
CodeName *string `json:"codeName,omitempty"`
}
