/*
 * vserver
 *
 * VPC Compute 관련 API<br/>https://ncloud.beta-apigw.ntruss.com/vserver/v2
 *
 * API version: 2020-08-27T03:07:34Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type CreateAccessControlGroupRequest struct {

	// REGION코드
RegionCode *string `json:"regionCode,omitempty"`

	// ACG이름
AccessControlGroupName *string `json:"accessControlGroupName,omitempty"`

	// ACG설명
AccessControlGroupDescription *string `json:"accessControlGroupDescription,omitempty"`

	// VPC번호
VpcNo *string `json:"vpcNo"`
}
