/*
 * vserver
 *
 * VPC Compute 관련 API<br/>https://ncloud.beta-apigw.ntruss.com/vserver/v2
 *
 * API version: 2020-09-04T05:39:38Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type ImportLoginKeyRequest struct {

	// 키이름
KeyName *string `json:"keyName,omitempty"`

	// 공개키
PublicKey *string `json:"publicKey"`
}
