/*
 * vserver
 *
 * VPC Compute 관련 API<br/>https://ncloud.apigw.ntruss.com/vserver/v2
 *
 * API version: 2020-07-09T01:14:38Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type PrivateKey struct {

	// 키이름
KeyName *string `json:"keyName,omitempty"`

	// 개인키
PrivateKey *string `json:"privateKey,omitempty"`
}
