/*
 * vserver
 *
 * VPC Compute 관련 API<br/>https://ncloud.beta-apigw.ntruss.com/vserver/v2
 *
 * API version: 2020-09-04T05:39:38Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type Region struct {

	// REGION코드
RegionCode *string `json:"regionCode,omitempty"`

	// REGION이름
RegionName *string `json:"regionName,omitempty"`
}
