/*
 * vserver
 *
 * VPC Compute 관련 API<br/>https://ncloud.apigw.ntruss.com/vserver/v2
 *
 * API version: 2020-07-09T01:14:38Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type RootPasswordServerInstanceParameter struct {

	// 서버인스턴스번호
ServerInstanceNo *string `json:"serverInstanceNo"`

	// 개인키
PrivateKey *string `json:"privateKey,omitempty"`
}
