/*
 * vserver
 *
 * VPC Compute 관련 API<br/>https://ncloud.beta-apigw.ntruss.com/vserver/v2
 *
 * API version: 2020-08-27T03:07:34Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type Zone struct {

	// ZONE이름
ZoneName *string `json:"zoneName,omitempty"`

	// ZONE코드
ZoneCode *string `json:"zoneCode,omitempty"`

	// REGION코드
RegionCode *string `json:"regionCode,omitempty"`

	// ZONE설명
ZoneDescription *string `json:"zoneDescription,omitempty"`
}
