/*
 * vpc
 *
 * VPC Network 관련 API<br/>https://ncloud.beta-apigw.ntruss.com/vpc/v2
 *
 * API version: 2020-08-27T11:47:46Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vpc

type CommonCode struct {

	// 코드
Code *string `json:"code,omitempty"`

	// 코드명
CodeName *string `json:"codeName,omitempty"`
}
