/*
 * vpc
 *
 * VPC Network 관련 API<br/>https://ncloud.beta-apigw.ntruss.com/vpc/v2
 *
 * API version: 2020-08-04T12:59:37Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vpc

type CreateNatGatewayInstanceRequest struct {

	// REGION코드
RegionCode *string `json:"regionCode,omitempty"`

	// NATGateway설명
NatGatewayDescription *string `json:"natGatewayDescription,omitempty"`

	// NATGateway이름
NatGatewayName *string `json:"natGatewayName,omitempty"`

	// VPC번호
VpcNo *string `json:"vpcNo"`

	// ZONE코드
ZoneCode *string `json:"zoneCode"`
}
