/*
 * vpc
 *
 * VPC Network 관련 API<br/>https://ncloud.beta-apigw.ntruss.com/vpc/v2
 *
 * API version: 2020-08-04T12:59:37Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vpc

type DeleteVpcPeeringInstanceRequest struct {

	// REGION코드
RegionCode *string `json:"regionCode,omitempty"`

	// VPCPeering인스턴스번호
VpcPeeringInstanceNo *string `json:"vpcPeeringInstanceNo"`
}
