/*
 * vpc
 *
 * VPC Network 관련 API<br/>https://ncloud.beta-apigw.ntruss.com/vpc/v2
 *
 * API version: 2020-08-04T12:59:37Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vpc

type GetRouteTableDetailRequest struct {

	// REGION코드
RegionCode *string `json:"regionCode,omitempty"`

	// 라우트테이블번호
RouteTableNo *string `json:"routeTableNo"`
}
